### PR TITLE
Fix: move increment id because the first fund was with id 0.

### PR DESCRIPTION
**Pull request by EmmanuelAR**
Fix: move increment id because the first fund was with id 0.

### CODE REVIEW

**Comment by adrianvrj** [comment]
@EmmanuelAR what is the reason for this change? it is known in programming that ids normally start with 0, as in any array the first position is taken as 0

**Comment by adrianvrj** [comment]
I get it now, 0 would denote NULL if we are talking about table objects, great catch g, appreciate the change

**Review by adrianvrj — APPROVED** [review]

**Comment by EmmanuelAR** [comment]
I see like in order, if we want to show the funds will be weird to see a id in 0, another point is that i see like a sql tables, the first register will !

**Comment by adrianvrj** [comment]
@EmmanuelAR is this bug present in the other manager?

**Comment by EmmanuelAR** [comment]
> @EmmanuelAR is this bug present in the other manager?

No, for the donator manager we use the donator address as key

**Pull request merged**
