### PR TITLE
[test] Test issued when the fund contract receives a donation

### LINKED ISSUE #144: [test] Test event emit when fund contract receives donation
### This issue will be part of ODHack9.0, please apply via Onlydust app
- See #138 for more context.
- Add a test to make sure the event is emitting correctly with all the values expected.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- Event is being emitted correctly.
- Tests pass successfully.

### PR DESCRIPTION
**Pull request by salazarsebas**
# Pull Request

- [x] Closes #144 
- [x] Added tests (if necessary)
- [x] Run tests
- [x] Run formatting
- [x] Commented the code

## Changes description

These tests verify that issue 183 #138 is correctly executed and make sure that the event emits the expected values, the tests pass successfully. In addition to some modifications in the readme.

## Current output

code

tests

readme_changes

## Comments

I hope the solution solves what you requested, please let me know of any changes I need to make. Best regards.

### CODE REVIEW

**Comment by salazarsebas** [comment]
Please tell me what you think of the pr. @adrianvrj @EmmanuelAR  ⛩️🚀⌨️

**Review by adrianvrj — APPROVED** [review]
Lgtm! Great work

**Review by EmmanuelAR — APPROVED** [review]
LGTM!

**Comment by salazarsebas** [comment]
@EmmanuelAR and @adrianvrj , thank you very much for the opportunity. 🤝🏼🚀

**Comment by EmmanuelAR** [comment]
Thks to u Ser 🙌🏻

**Pull request merged**
