### PR TITLE
Feat: Add users funds page

### PR DESCRIPTION
**Pull request by wugalde19**
# Pull Request

- [X] Closes https://github.com/web3wagers/gostarkme/issues/93

## Changes description
1.  Add `myfunds` page
2. Create `FundCard` component
3. Create `UserFunds` component
4. Allow `Button` UI component to receive `className` for custom classes 

#### TODOs added
// TODO: Implement new fund action
// TODO: Implement funds fetching using 'userAddress'
// TODO: Implement fund deletion based on a unique id or receive the fund object and delete it

## Current output
Screenshot 2024-09-29 at 10 16 19 PM
Screenshot 2024-09-29 at 10 22 07 PM
Screenshot 2024-09-29 at 10 17 06 PM
Screenshot 2024-09-29 at 10 21 47 PM

## Time spent breakdown

1.5 - 2 hours

## Comments
- URL to access and check the page: http://localhost:3000/app/myfunds/0x01a9222d495ffdba8d0d4c32c53b19348acf525fc8a34bf1c95476bc977e1c23
- Figma design specs: https://www.figma.com/design/SCiGViaoPT9UTrT7CsLbAt/Go-Stark-Me?node-id=0-1&node-type=canvas&t=9SSNtvTO4KS4DcIC-0

### CODE REVIEW

**Review by adrianvrj — APPROVED** [review]
LGTM, nice work!

**Comment by adrianvrj** [comment]
@wugalde19 it seems like something is missing, please take a look at the error in the pipeline, you should add some static params or something like that in order to make production deploy work

**Comment by wugalde19** [comment]
@adrianvrj  I've fixed the issue
I tried the build locally and it seems to be working fine
Please let me know if you want me to apply some other change(s)
image

**Comment by adrianvrj** [comment]
@wugalde19 great work homie, merged!

**Comment by wugalde19** [comment]
> @wugalde19 great work homie, merged!

Thanks @adrianvrj 🫡

**Pull request merged**
