### PR TITLE
Fund test event emit

### LINKED ISSUE #145: [test] Test event emit when fund contract receives vote
### This issue will be part of ODHack9.0, please apply via Onlydust app
- See #137 for more context.
- Add a test to make sure the event is emitting correctly with all the values expected.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- Event is being emitted correctly.
- Tests pass successfully.

### PR DESCRIPTION
**Pull request by juandiegocv27**
# Pull Request

-  Closes #145 
-  Added tests: test_new_vote_received_event_emitted_successful

## Changes:

This adds a test to verify that the NewVoteReceived event is correctly emitted when a user votes. It checks that the event includes the right voter address, fund address, and vote count.

## Current output:

image

### CODE REVIEW

**Comment by juandiegocv27** [comment]
@adrianvrj  @EmmanuelAR please review this fresh pr 🔥

**Comment by EmmanuelAR** [comment]
Thks, we will review it

**Review by adrianvrj — APPROVED** [review]
Lgtm!

**Review by EmmanuelAR — APPROVED** [review]
LGTM

**Pull request merged**
